# Generated by Django 2.1.1 on 2018-10-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
    ]
